import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Application.java
//  @ Date : 10/19/2015
//  @ Author : 
//
//




public class Application {
    public static void main(String[] args) {
    	PercentCounter pc = new PercentCounter();
    	PrintWriter pw;
		try {
			pw = new PrintWriter(new FileWriter("file.txt"));
		
    	FileLogger fl = new FileLogger("file.txt", pw);
    	StdOutLogger sl = new StdOutLogger();
    	pc.register(fl);
    	pc.register(sl);
    	pc.run();
    	pw.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
}
