import java.util.ArrayList;
import java.util.Collection;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Observable.java
//  @ Date : 10/19/2015
//  @ Author : 
//
//




public class Observable {
    private Collection<Observer> observers=new ArrayList<>();
    public void register(Observer observer) {
    	observers.add(observer);
    }
    
    public void unregister(Observer observer) {
    	observers.remove(observer);
    }
    
    public void reportToObservers() {
    	for (Observer o : observers)
    		o.report(this);
    }
}
