//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Observer.java
//  @ Date : 10/19/2015
//  @ Author : 
//
//




public interface Observer {
    public void report(Observable observable);
}
