//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PercentCounter.java
//  @ Date : 10/19/2015
//  @ Author : 
//
//




public class PercentCounter extends Observable {
	private int percent;
	public void run() {
		for (percent=0; percent<100; percent++){
			if (percent%10==0)
				reportToObservers();
		}
	}
	public String toString(){
		return percent+"%";
	}
}
